version: "3.9"

services:
  backend:
    build:
      context: ./api-python
      dockerfile: dockerfile 
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Wordle
      dockerfile: dockerfile
      args:
        VITE_API_URL: http://backend:8000
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
