version: "3.9"

services:
  backend:
    build:
      context: ./api-python
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Wordle
      dockerfile: dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Wordle:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
