FROM python:3.11-slim

WORKDIR /app

# Copiamos todo el contenido del backend
COPY . .

# Instala FastAPI y Uvicorn, y lo que más uses
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
